export const constants = {
    CREATE_USER: 'CREATE_USER',
    DELETE_USER: 'DELETE_USER',
    UPDATE_USER: 'UPDATE_USER',
    USER_TO_EDIT: 'USER_TO_EDIT',
    CLEAR_USER_TO_EDIT: 'CLEAR_USER_TO_EDIT'
}